
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action newAction;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action NewAction;
	private global::Gtk.Action OpenAction;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Action SaveAsAction;
	private global::Gtk.Action ExitAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction1;
	private global::Gtk.Action saveAsAction1;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action helpAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label5;
	private global::Gtk.Entry txtMAMEPath;
	private global::Gtk.Button btnMAMEBrowse;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label6;
	private global::Gtk.Entry txtROMSPath;
	private global::Gtk.Button btnROMSBrowse;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label1;
	private global::Gtk.Entry txtSnapsPath;
	private global::Gtk.Button btnSnapBrowse;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView nvGamesList;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Alignment alignment5;
	private global::Gtk.Button btnUp;
	private global::Gtk.Button btnDown;
	private global::Gtk.Alignment alignment6;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.Button btnScan;
	private global::Gtk.Button btnDelete;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.Label label3;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction, null);
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction1, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction1, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction1, null);
		this.saveAsAction1 = new global::Gtk.Action ("saveAsAction1", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction1, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, "gtk-help");
		this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.helpAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Cabrio Config Builder");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction1' action='openAction1'/><menuitem name='saveAction1' action='saveAction1'/><menuitem name='saveAsAction1' action='saveAsAction1'/><separator/><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><toolitem name='saveAsAction' action='saveAsAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 1;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("MAME Path:");
		this.hbox5.Add (this.label5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.txtMAMEPath = new global::Gtk.Entry ();
		this.txtMAMEPath.CanFocus = true;
		this.txtMAMEPath.Name = "txtMAMEPath";
		this.txtMAMEPath.IsEditable = true;
		this.txtMAMEPath.InvisibleChar = '•';
		this.hbox5.Add (this.txtMAMEPath);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txtMAMEPath]));
		w5.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnMAMEBrowse = new global::Gtk.Button ();
		this.btnMAMEBrowse.CanFocus = true;
		this.btnMAMEBrowse.Name = "btnMAMEBrowse";
		this.btnMAMEBrowse.UseUnderline = true;
		this.btnMAMEBrowse.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox5.Add (this.btnMAMEBrowse);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnMAMEBrowse]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("ROMS Path:");
		this.hbox6.Add (this.label6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.txtROMSPath = new global::Gtk.Entry ();
		this.txtROMSPath.CanFocus = true;
		this.txtROMSPath.Name = "txtROMSPath";
		this.txtROMSPath.IsEditable = true;
		this.txtROMSPath.InvisibleChar = '•';
		this.hbox6.Add (this.txtROMSPath);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtROMSPath]));
		w9.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnROMSBrowse = new global::Gtk.Button ();
		this.btnROMSBrowse.CanFocus = true;
		this.btnROMSBrowse.Name = "btnROMSBrowse";
		this.btnROMSBrowse.UseUnderline = true;
		this.btnROMSBrowse.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox6.Add (this.btnROMSBrowse);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnROMSBrowse]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Snapshot Path:");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtSnapsPath = new global::Gtk.Entry ();
		this.txtSnapsPath.CanFocus = true;
		this.txtSnapsPath.Name = "txtSnapsPath";
		this.txtSnapsPath.IsEditable = true;
		this.txtSnapsPath.InvisibleChar = '•';
		this.hbox1.Add (this.txtSnapsPath);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtSnapsPath]));
		w13.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnSnapBrowse = new global::Gtk.Button ();
		this.btnSnapBrowse.CanFocus = true;
		this.btnSnapBrowse.Name = "btnSnapBrowse";
		this.btnSnapBrowse.UseUnderline = true;
		this.btnSnapBrowse.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox1.Add (this.btnSnapBrowse);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSnapBrowse]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox6.Add (this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox1]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.notebook2.Add (this.vbox6);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Paths");
		this.notebook2.SetTabLabel (this.vbox6, this.label2);
		this.label2.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nvGamesList = new global::Gtk.NodeView ();
		this.nvGamesList.CanFocus = true;
		this.nvGamesList.Name = "nvGamesList";
		this.GtkScrolledWindow.Add (this.nvGamesList);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
		w18.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.vbox5.Add (this.alignment5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.alignment5]));
		w19.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnUp = new global::Gtk.Button ();
		this.btnUp.CanFocus = true;
		this.btnUp.Name = "btnUp";
		this.btnUp.UseStock = true;
		this.btnUp.UseUnderline = true;
		this.btnUp.Label = "gtk-go-up";
		this.vbox5.Add (this.btnUp);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnUp]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnDown = new global::Gtk.Button ();
		this.btnDown.CanFocus = true;
		this.btnDown.Name = "btnDown";
		this.btnDown.UseStock = true;
		this.btnDown.UseUnderline = true;
		this.btnDown.Label = "gtk-go-down";
		this.vbox5.Add (this.btnDown);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnDown]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment6.Name = "alignment6";
		this.vbox5.Add (this.alignment6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.alignment6]));
		w22.Position = 3;
		this.hbox2.Add (this.vbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w24.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox3.Add (this.alignment1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
		w25.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnScan = new global::Gtk.Button ();
		this.btnScan.CanFocus = true;
		this.btnScan.Name = "btnScan";
		this.btnScan.UseUnderline = true;
		this.btnScan.Label = global::Mono.Unix.Catalog.GetString ("Scan directory");
		this.hbox3.Add (this.btnScan);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnScan]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btnDelete = new global::Gtk.Button ();
		this.btnDelete.CanFocus = true;
		this.btnDelete.Name = "btnDelete";
		this.btnDelete.UseUnderline = true;
		this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete item");
		this.hbox3.Add (this.btnDelete);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnDelete]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox3.Add (this.alignment2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment2]));
		w28.Position = 3;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		this.notebook2.Add (this.vbox2);
		global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.vbox2]));
		w30.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Games List");
		this.notebook2.SetTabLabel (this.vbox2, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
		w31.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w32.Position = 3;
		w32.Expand = false;
		w32.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 596;
		this.DefaultHeight = 482;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenAction1Activated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.btnMAMEBrowse.Clicked += new global::System.EventHandler (this.OnBtnMAMEBrowseClicked);
		this.btnROMSBrowse.Clicked += new global::System.EventHandler (this.OnBtnROMSBrowseClicked);
		this.btnSnapBrowse.Clicked += new global::System.EventHandler (this.OnBtnSnapBrowseClicked);
		this.btnScan.Clicked += new global::System.EventHandler (this.OnBtnScanClicked);
	}
}
